add new step to validate

diff --git a/.github/workflows/pr_validate.yaml b/.github/workflows/pr_validate.yaml
--- a/.github/workflows/pr_validate.yaml
+++ b/.github/workflows/pr_validate.yaml
@@ -15,6 +15,7 @@ jobs:
       group: ${{ github.head_ref }}
       cancel-in-progress: true
     outputs:
+      url: ${{ steps.extract-staging.outputs.url }}
       sandbox: ${{ steps.extract-staging.outputs.sandbox }}
       should_e2e_run: ${{ steps.check-e2e-trigger.outcome }}
     steps:
@@ -96,6 +97,8 @@ jobs:
     runs-on: ubuntu-20.04
     needs: lint-pr-body
     if: needs.lint-pr-body.outputs.should_e2e_run == 'success'
+    outputs:
+      result: ${{ steps.run-integration-test.outcome }}
     concurrency: 
       group: ${{ github.sha }}
     steps:
@@ -178,3 +181,34 @@ jobs:
           head-branch-regex: '${{ github.head_ref }}'
           body-template: "${{  steps.create-unchecked-pr-body.outputs.body }}"
           body-update-action: 'replace'
+
+  conclude-intergration-tests:
+    name: Conclude integration tests
+    runs-on: ubuntu-20.04
+    needs: [lint-pr-body, run-integration-tests]
+    concurrency: 
+      group: ${{ github.head_ref }}
+    steps:
+      - id: conclude
+        name: Conclude integation test
+        run: |-
+
+          IS_STAGING_NA = ${{ needs.lint-pr-body.outputs.url == 'N/A' }}
+          echo "Does the PR need to be checked against integration tests?"
+          echo $IS_STAGING_NA
+
+          if [ {{ IS_STAGING_NA }} -eq 1 ]; then
+            echo "This PR is marked as not having to go through integration tests."
+            exit 0
+          fi
+          
+          INTEGRATION_TEST_RESULT=${{ needs.run-integration-tests.outcome }}
+          echo "Result of integration tests:"
+          echo $INTEGRATION_TEST_RESULT
+
+          if [ {{ INTEGRATION_TEST_RESULT }} == 'success' ]; then
+            echo "Integration tests passed."
+            exit 0
+          else
+            echo "Integration tests failed."
+            exit 1
